### ISSUE TITLE
Syntax errors all over the place

### ISSUE THREAD

**Issue by Explosion-Scratch** [nickbreaton/vitest-svelte-kit#11]
Simply doing this in svelte config:
```js
export default () => ({vite: {}})
```
and then in `vite.config.js`:
```js
import { extractFromSvelteConfig } from 'vitest-svelte-kit';

let cfg = extractFromSvelteConfig();

cfg.then(console.log); // Just the plugins added by this package

export default cfg;
```

is giving syntax errors seemingly at random:
```
vite v2.9.9 building for production...
✓ 0 modules transformed.
[vite-plugin-svelte] /workspace/stackoverflow_import/src/routes/__layout.svelte:180:46 RightParenthesis is expected
file: /workspace/stackoverflow_import/src/routes/__layout.svelte:180:46
 178 |      height: 3px;
 179 |      border: 0;
 180 |      background-image: linear-gradient(to right, @primary-500, spin(@primary-500, -20), transparent);
                                                        ^
 181 |    }
 182 |    :global(.gradient-text) {
> /workspace/stackoverflow_import/src/routes/__layout.svelte:180:46 RightParenthesis is expected
    at error (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:17691:19)
    at Parser$1.error (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:17767:9)
    at Object.read_style [as read] (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:14456:20)
    at tag (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:16817:33)
    at new Parser$1 (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:17726:21)
    at parse$3 (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:17858:20)
    at compile (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:31871:17)
    at compileSvelte2 (file:///workspace/stackoverflow_import/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.47_svelte@3.46.4+vite@2.9.9/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:321:20)
    at async Object.transform (file:///workspace/stackoverflow_import/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.47_svelte@3.46.4+vite@2.9.9/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1727:25)
[!] Error: unfinished hook action(s) on exit:
(vite:load-fallback) load "/workspace/stackoverflow_import/.svelte-kit/runtime/client/start.js"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/__error.svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/challenges/__layout.svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/modules/__layout.svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/about.svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/api/verify/[slug].svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/challenges/[slug]/submit.svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/challenges/index.svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/graphql_test.svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/help/ask.svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/help/faq/[slug].svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/help/faq.svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/help/index.svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/help/questions/[slug].svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/home.svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/index.svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/login.svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/modules/index.svelte"
(vite:load-fallback) load "/workspace/stackoverflow_import/src/routes/signup.svelte"

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Explosion-Scratch** [comment]
Sometimes the error is this too:
```
[vite-plugin-svelte] /workspace/stackoverflow_import/src/routes/__error.svelte:17:1 The keyword 'let' is reserved
file: /workspace/stackoverflow_import/src/routes/__error.svelte:17:1
 15 |  
 16 |  function create_fragment(ctx) {
 17 |    let error_1;
         ^
 18 |    let current;
 19 |  
> /workspace/stackoverflow_import/src/routes/__error.svelte:17:1 The keyword 'let' is reserved
    at error (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:17691:19)
    at Parser$1.error (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:17767:9)
    at Parser$1.acorn_error (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:17761:14)
    at read_expression (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:8783:16)
    at mustache (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:17582:28)
    at new Parser$1 (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:17726:21)
    at parse$3 (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:17858:20)
    at compile (file:///workspace/stackoverflow_import/node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/compiler.mjs:31871:17)
    at compileSvelte2 (file:///workspace/stackoverflow_import/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.47_svelte@3.46.4+vite@2.9.9/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:321:20)
    at async Object.transform (file:///workspace/stackoverflow_import/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.47_svelte@3.46.4+vite@2.9.9/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1727:25)
[!] Error: unfinished hook action(s) on exit:
(vite:load-fallback) load "/workspace/stackoverflow_import/.svelte-kit/runtime/client/start.js"
[Every single file here]

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Explosion-Scratch** [comment]
This error changes but does not go away when deleting all content in __error.svelte

**Comment by Explosion-Scratch** [comment]
And does not happen when simply using `defineConfig` in `vite.config.js` or deleting `vite.config.js`
